# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf1eb635ef69e66ce4f1b88728d109a0c6ee94a2667c808a468bbda98fb43c4c547639caafe3f9eb31b185245980319de811245e35e31d08b79a5d3d30f84b0

test:
  secret_key_base: 6be5c2d676b16490ec2ad349d93b620cdde9092648a677a7ebaf80449e1e0f5dd43eecb08a6fbaebbceef001ee0f80c52b7afbba5526da15151125cbd3a1b40c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
